name: (DESATIVADO) Update data.json (FAPEAM)

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Disabled
        run: echo "Workflow desativado. Atualização do site é manual."
